version: '3'
services:
  notebook:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "$PWD:/home/jovyan/work"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  tensorboard:
    build: 
      context: .
      dockerfile: Dockerfile2
    command: tensorboard --logdir /logs --bind_all
    ports:
      - "6006:6006"
    volumes:
      - "$PWD/logs:/logs"
    environment:
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
